name: Build
on: [push, pull_request]

jobs:
  build-windows:
    runs-on: windows-latest-mingw
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Set up MinGW
        uses: egor-tensin/setup-mingw@v2
        with:
          platform: x64
      - name: build everything
        run: |
          gcc -o .\build.exe .\build\build.c
          ./build.exe run
          ./build.exe test
